#! /bin/sh
# /etc/init.d/led-matrix

### BEGIN INIT INFO
# Provides:          led-matrix
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting ledmatrix"
    # run application you want to start
    sudo /home/pi/go/src/github.com/aurisl/led-matrix/led-matrix --working-dir=/home/pi/go/src/github.com/aurisl/led-matrix >> /var/log/led-matrix.log 2>&1 &
    ;;
  stop)
    echo "Stopping ledmatrix"
    # kill application you want to stop
    led-matrix
    ;;
  *)
    echo "Usage: /etc/init.d/ledmatrix {start|stop}"
    exit 1
    ;;
esac

exit 0